In [1]:
import sys
print(sys.version)

3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]

In [95]:
import pandas as pd
import numpy as np

In [96]:
df = pd.read_csv('2022_6.csv')

DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.

In [97]:
df.head()

,created_date,tweet_id,author_id,text,is_retweet,retweet_id,retweet_author_id,dateid
0,2022-02-02 00:00:01,1488663461060096004,2.955079e+09,RT @F_Desouche: L'eurodéputée RN Maxette Pirba...,True,1.488611e+18,9.284914e+07,20220202
1,2022-02-02 00:00:01,1488663461106233351,1.472392e+09,RT @Wealth_Theory: @JustinTrudeau @EmmanuelMac...,True,1.488644e+18,1.090069e+18,20220202
2,2022-02-02 00:00:02,1488663462955810816,1.488225e+18,RT @Henrik_Palmgren: Klaus Schwab says that Vl...,True,1.487586e+18,2.231109e+09,20220202
3,2022-02-02 00:00:03,1488663470014971917,8.955909e+17,RT @JulienPain: Vous aviez entendu Eric Zemmou...,True,1.488576e+18,9.651232e+06,20220202
4,2022-02-02 00:00:04,1488663471373709314,1.466138e+18,@JustinTrudeau @EmmanuelMacron This you https:...,False,NaN,NaN,20220202

In [5]:
#pip install dask

In [6]:
import dask.dataframe as dd

In [7]:
csv_file_path = r'C:\Users\deadl\Downloads\Data_Science_project\2022_6.csv'
df_dask = dd.read_csv(csv_file_path)
print(df_dask.head())

ParserError: Error tokenizing data. C error: EOF inside string starting at row 258503

In [8]:
df_dask

Dask DataFrame Structure:
              created_date tweet_id author_id    text is_retweet retweet_id retweet_author_id dateid
npartitions=9
                    object    int64   float64  object       bool    float64           float64  int64
                       ...      ...       ...     ...        ...        ...               ...    ...
...                    ...      ...       ...     ...        ...        ...               ...    ...
                       ...      ...       ...     ...        ...        ...               ...    ...
                       ...      ...       ...     ...        ...        ...               ...    ...
Dask Name: read-csv, 1 graph layer

In [9]:
#pip install modin

In [10]:
import modin.pandas as mpd

In [11]:
csv_file_path = r'C:\Users\deadl\Downloads\Data_Science_project\2022_6.csv'
df_modin = mpd.read_csv(csv_file_path)

df_modin.head()

2023-08-12 15:20:16,417	INFO util.py:159 -- Outdated packages:
  ipywidgets==7.6.5 found, needs ipywidgets>=8
Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.
UserWarning: Ray execution environment not yet initialized. Initializing...
To remove this warning, run the following python code before doing dataframe operations:

    import ray
    ray.init(runtime_env={'env_vars': {'__MODIN_AUTOIMPORT_PANDAS__': '1'}})

2023-08-12 15:20:23,012	INFO worker.py:1621 -- Started a local Ray instance.
UserWarning: `read_*` implementation has mismatches with pandas:
Data types of partitions are different! Please refer to the troubleshooting section of the Modin documentation to fix this issue.

,created_date,tweet_id,author_id,text,is_retweet,retweet_id,retweet_author_id,dateid
0,2022-02-02 00:00:01,1488663461060096004,2.955079e+09,RT @F_Desouche: L'eurodéputée RN Maxette Pirba...,True,1.488611e+18,9.284914e+07,20220202
1,2022-02-02 00:00:01,1488663461106233351,1.472392e+09,RT @Wealth_Theory: @JustinTrudeau @EmmanuelMac...,True,1.488644e+18,1.090069e+18,20220202
2,2022-02-02 00:00:02,1488663462955810816,1.488225e+18,RT @Henrik_Palmgren: Klaus Schwab says that Vl...,True,1.487586e+18,2.231109e+09,20220202
3,2022-02-02 00:00:03,1488663470014971917,8.955909e+17,RT @JulienPain: Vous aviez entendu Eric Zemmou...,True,1.488576e+18,9.651232e+06,20220202
4,2022-02-02 00:00:04,1488663471373709314,1.466138e+18,@JustinTrudeau @EmmanuelMacron This you https:...,False,NaN,NaN,20220202

In [12]:
#pip install modin[ray]

In [38]:
import modin.pandas as rpd

In [39]:
csv_file_path = r'C:\Users\deadl\Downloads\Data_Science_project\2022_6.csv'
df_ray = rpd.read_csv(csv_file_path)

In [40]:
df_ray.head()

,created_date,tweet_id,author_id,text,is_retweet,retweet_id,retweet_author_id,dateid
0,2022-02-02 00:00:01,1488663461060096004,2.955079e+09,RT @F_Desouche: L'eurodéputée RN Maxette Pirba...,True,1.488611e+18,9.284914e+07,20220202
1,2022-02-02 00:00:01,1488663461106233351,1.472392e+09,RT @Wealth_Theory: @JustinTrudeau @EmmanuelMac...,True,1.488644e+18,1.090069e+18,20220202
2,2022-02-02 00:00:02,1488663462955810816,1.488225e+18,RT @Henrik_Palmgren: Klaus Schwab says that Vl...,True,1.487586e+18,2.231109e+09,20220202
3,2022-02-02 00:00:03,1488663470014971917,8.955909e+17,RT @JulienPain: Vous aviez entendu Eric Zemmou...,True,1.488576e+18,9.651232e+06,20220202
4,2022-02-02 00:00:04,1488663471373709314,1.466138e+18,@JustinTrudeau @EmmanuelMacron This you https:...,False,NaN,NaN,20220202

In [98]:
date_time_split = df['created_date'].str.split(' ', expand=True)

# Assign the date and time components to separate columns
df['date'] = date_time_split[0]
df['time'] = date_time_split[1]
df.drop(columns = ['created_date'], inplace = True)
df.rename(columns={'date': 'created_date'}, inplace=True)

In [99]:
df['author_id'] = pd.to_numeric(df['author_id'], errors='coerce')
df['author_id'] = df['author_id'].apply(lambda x: '{:.0f}'.format(x))
df['author_id'] = df['author_id'].astype(str)


df['retweet_id'] = pd.to_numeric(df['retweet_id'], errors='coerce')
df['retweet_id'] = df['retweet_id'].apply(lambda x: '{:.0f}'.format(x))
df['retweet_id'] = df['retweet_id'].astype(str)

df['retweet_author_id'] = pd.to_numeric(df['retweet_author_id'], errors='coerce')
df['retweet_author_id'] = df['retweet_author_id'].apply(lambda x: '{:.0f}'.format(x))
df['retweet_author_id'] = df['retweet_author_id'].astype(str)

In [100]:
#df_ray['dateid'] = pd.to_datetime(df_ray['dateid'], format='%Y%m%d').dt.strftime('%Y-%m-%d')
#df_ray['dateid'] = pd.to_datetime(df_ray['dateid'], format='%Y%m%d').dt.strftime('%Y-%m-%d')

#df_ray['dateid'] = pd.to_datetime(df_ray['dateid'], format='%Y%m%d').dt.strftime('%Y-%m-%d')

df['dateid'] = df['dateid'].astype(str)

df['dateid'] = pd.to_datetime(df['dateid'], format='%Y%m%d').dt.strftime('%Y-%m-%d')

In [101]:
df

,tweet_id,author_id,text,is_retweet,retweet_id,retweet_author_id,dateid,created_date,time
0,1488663461060096004,2955078990,RT @F_Desouche: L'eurodéputée RN Maxette Pirba...,True,1488611484804554752,92849144,2022-02-02,2022-02-02,00:00:01
1,1488663461106233351,1472392472,RT @Wealth_Theory: @JustinTrudeau @EmmanuelMac...,True,1488644119543091200,1090068803562684416,2022-02-02,2022-02-02,00:00:01
2,1488663462955810816,1488224897369198592,RT @Henrik_Palmgren: Klaus Schwab says that Vl...,True,1487585675520057088,2231109295,2022-02-02,2022-02-02,00:00:02
3,1488663470014971917,895590923119329280,RT @JulienPain: Vous aviez entendu Eric Zemmou...,True,1488575637472305152,9651232,2022-02-02,2022-02-02,00:00:03
4,1488663471373709314,1466137712952581888,@JustinTrudeau @EmmanuelMacron This you https:...,False,nan,nan,2022-02-02,2022-02-02,00:00:04
...,...,...,...,...,...,...,...,...,...
2333090,1487616316026626048.0,108434962,"Pour un #AvenirEnCommun et l'#UnionPopulaire, ...",NaN,nan,nan,2022-02-01,2022-01-30,02:39:02
2333091,1486594965308383232.0,1361050343170338816,"Je ne sais pas si vous pourrez, @Anne_Hidalgo,...",NaN,nan,nan,2022-02-01,2022-01-27,07:00:33
2333092,1485045259189067776.0,1455938622515973888,Kids asks Nigeria military and police to stop ...,NaN,nan,nan,2022-02-01,2022-01-23,00:22:35
2333093,1487934553604096000.0,1431849697002483712,@ChTaubira Un plébiscite en ligne sans program...,NaN,nan,nan,2022-02-01,2022-01-30,23:43:36
2333094,1487421629688946688.0,1329432931354497024,"""At least 2 million people in the northern #Et...",NaN,nan,nan,2022-02-01,2022-01-29,13:45:26

In [102]:
#pip install pyyaml

In [103]:
import yaml

In [104]:
column_names = list(['created_date',
    'time',
    'tweet_id',
    'author_id',
    'text',
    'is_retweet',
    'retweet_id',
    'retweet_author_id',
    'dateid'
])
with open('column_names.yaml', 'w') as yaml_file:
    yaml.dump(column_names, yaml_file)

In [105]:
with open('column_names.yaml', 'r') as yaml_file:
    expected_column_names = yaml.safe_load(yaml_file)

if len(df.columns) == len(expected_column_names) and all(col in df.columns for col in expected_column_names):
    print("Column validation successful.")
else:
    print("Column validation failed.")

Column validation successful.

In [106]:
df

,tweet_id,author_id,text,is_retweet,retweet_id,retweet_author_id,dateid,created_date,time
0,1488663461060096004,2955078990,RT @F_Desouche: L'eurodéputée RN Maxette Pirba...,True,1488611484804554752,92849144,2022-02-02,2022-02-02,00:00:01
1,1488663461106233351,1472392472,RT @Wealth_Theory: @JustinTrudeau @EmmanuelMac...,True,1488644119543091200,1090068803562684416,2022-02-02,2022-02-02,00:00:01
2,1488663462955810816,1488224897369198592,RT @Henrik_Palmgren: Klaus Schwab says that Vl...,True,1487585675520057088,2231109295,2022-02-02,2022-02-02,00:00:02
3,1488663470014971917,895590923119329280,RT @JulienPain: Vous aviez entendu Eric Zemmou...,True,1488575637472305152,9651232,2022-02-02,2022-02-02,00:00:03
4,1488663471373709314,1466137712952581888,@JustinTrudeau @EmmanuelMacron This you https:...,False,nan,nan,2022-02-02,2022-02-02,00:00:04
...,...,...,...,...,...,...,...,...,...
2333090,1487616316026626048.0,108434962,"Pour un #AvenirEnCommun et l'#UnionPopulaire, ...",NaN,nan,nan,2022-02-01,2022-01-30,02:39:02
2333091,1486594965308383232.0,1361050343170338816,"Je ne sais pas si vous pourrez, @Anne_Hidalgo,...",NaN,nan,nan,2022-02-01,2022-01-27,07:00:33
2333092,1485045259189067776.0,1455938622515973888,Kids asks Nigeria military and police to stop ...,NaN,nan,nan,2022-02-01,2022-01-23,00:22:35
2333093,1487934553604096000.0,1431849697002483712,@ChTaubira Un plébiscite en ligne sans program...,NaN,nan,nan,2022-02-01,2022-01-30,23:43:36
2333094,1487421629688946688.0,1329432931354497024,"""At least 2 million people in the northern #Et...",NaN,nan,nan,2022-02-01,2022-01-29,13:45:26

In [107]:
df.author_id.dtype

dtype('O')

In [108]:
output_file = 'output_data.txt.gz'
df.to_csv(output_file, sep='|', index=False, compression='gzip')

Read the gz file

In [109]:
file_path = 'output_data.txt.gz'

# Read the gzipped file using pandas
df_gz = pd.read_csv(file_path, sep='|', compression='gzip')

DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.

In [110]:
df_gz

,tweet_id,author_id,text,is_retweet,retweet_id,retweet_author_id,dateid,created_date,time
0,1488663461060096004,2.955079e+09,RT @F_Desouche: L'eurodéputée RN Maxette Pirba...,True,1.488611e+18,9.284914e+07,2022-02-02,2022-02-02,00:00:01
1,1488663461106233351,1.472392e+09,RT @Wealth_Theory: @JustinTrudeau @EmmanuelMac...,True,1.488644e+18,1.090069e+18,2022-02-02,2022-02-02,00:00:01
2,1488663462955810816,1.488225e+18,RT @Henrik_Palmgren: Klaus Schwab says that Vl...,True,1.487586e+18,2.231109e+09,2022-02-02,2022-02-02,00:00:02
3,1488663470014971917,8.955909e+17,RT @JulienPain: Vous aviez entendu Eric Zemmou...,True,1.488576e+18,9.651232e+06,2022-02-02,2022-02-02,00:00:03
4,1488663471373709314,1.466138e+18,@JustinTrudeau @EmmanuelMacron This you https:...,False,NaN,NaN,2022-02-02,2022-02-02,00:00:04
...,...,...,...,...,...,...,...,...,...
2333090,1487616316026626048.0,1.084350e+08,"Pour un #AvenirEnCommun et l'#UnionPopulaire, ...",NaN,NaN,NaN,2022-02-01,2022-01-30,02:39:02
2333091,1486594965308383232.0,1.361050e+18,"Je ne sais pas si vous pourrez, @Anne_Hidalgo,...",NaN,NaN,NaN,2022-02-01,2022-01-27,07:00:33
2333092,1485045259189067776.0,1.455939e+18,Kids asks Nigeria military and police to stop ...,NaN,NaN,NaN,2022-02-01,2022-01-23,00:22:35
2333093,1487934553604096000.0,1.431850e+18,@ChTaubira Un plébiscite en ligne sans program...,NaN,NaN,NaN,2022-02-01,2022-01-30,23:43:36
2333094,1487421629688946688.0,1.329433e+18,"""At least 2 million people in the northern #Et...",NaN,NaN,NaN,2022-02-01,2022-01-29,13:45:26

In [94]:
df_gz.author_id.dtype

dtype('float64')